services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: home-radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - ./radarr/config:/config
      - /mnt/hdd/media:/media
      - /mnt/hdd/media/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: home-sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - ./sonarr/config:/config
      - /mnt/hdd/media:/media
      - /mnt/hdd/media/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: home-prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - ./prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: home-bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - ./bazarr/config:/config
      - /mnt/hdd/media:/media #optional
        # - ./media/series:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped
  qBittorrentvpn:
    container_name: home-qBittorrentvpn
    image: markusmcnugen/qbittorrentvpn
    restart: unless-stopped
    privileged: true
    ports:
      - "8080:8080"
      - "8999:8999"
      - "8999:8999/udp"
    volumes:
      - ./qBittorrentvpn:/config
      - /mnt/hdd/media/downloads:/downloads
    env_file:
      - qBittorrentvpn.env
