services:
  nginx:
    image: nginx:latest
    container_name: home-web
    restart: unless-stopped
    ports:
      - "80:80"   
    volumes:
      - ./web:/usr/share/nginx/html:ro
  homeassistant:
    container_name: home-homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
      # network_mode: host
    ports:
      - "8123:8123"
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: home-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped
    volumes:
      - ./mosquitto/config:/mosquitto/config
  pv2mqtt:
    image: ghcr.io/wez/govee2mqtt:latest
    container_name: home-govee2mqtt
    restart: unless-stopped
    env_file:
      - govee2mqtt.env
    # Host networking is required
    network_mode: host
  plex:
    container_name: home-plex
    image: plexinc/pms-docker
    restart: unless-stopped
    env_file:
      - plex.env
    network_mode: host
    volumes:
      - ./plex/config:/config
      - ./plex/transcode:/transcode
      - ./media:/data
  qBittorrentvpn:
    container_name: home-qBittorrentvpn
    image: markusmcnugen/qbittorrentvpn
    restart: unless-stopped
    privileged: true
    ports:
      - "8080:8080"
      - "8999:8999"
      - "8999:8999/udp"
    volumes:
      - ./qBittorrentvpn:/config
      - ./media:/downloads
    env_file:
      - qBittorrentvpn.env
  jellyfin:
    image: jellyfin/jellyfin
    container_name: home-jellyfin
    network_mode: 'host'
    volumes:
      - ./jellyfin/config:/config
      - ./pjellyfin/cache:/cache
      - type: bind
        source: ./media
        target: /media
      # - type: bind
      #   source: /path/to/media2
      #   target: /media2
      #   read_only: true
      # Optional - extra fonts to be used during transcoding with subtitle burn-in
      # - type: bind
      #   source: /path/to/fonts
      #   target: /usr/local/share/fonts/custom
      #   read_only: true
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    # environment:
    #   - JELLYFIN_PublishedServerUrl=http://example.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  filebrowser:
    image: filebrowser/filebrowser
    container_name: home-filebrowser
    ports:
      - "8081:80" 
    volumes:
      - ./media:/srv               # Mounts the root directory to /srv
      - ./filebrowser/filebrowser.db:/database/filebrowser.db # Mounts the database file
      - ./filebrowser/.filebrowser.json:/.filebrowser.json # Mounts the configuration file
    user: "${UID}:${GID}"
  speedtest:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: home-speedtest
    env_file:
      - speedtest.env
    volumes:
      - ./speedtest-tracker/data:/config
    ports:
      - 8082:80
    restart: unless-stopped
